#!/bin/sh

main_url="$1"

# Help message
print_help() {
    echo    "$0 <url>"
    echo    "    Scrapes albums and EPs from \"*.bandcamp.com/music*\""
    echo
    echo    "    Example usage:"
    echo -n "        $0 \"https://lyndsiealguire.bandcamp.com/music\""
    echo    " > result.txt"
}

# Check that a url was provided
[ "$main_url" = "" ] && print_help && exit

# Get the root url of the bandcamp
root_url="$(echo $main_url | sed -e 's/\(http.*bandcamp.com\).*/\1/g')"

# Get the contents of the music section
music_section_contents=$(curl "$root_url/music")

# Get urls to albums/ep's
album_urls=$(echo "$music_section_contents" | grep '/album/')
album_urls=$(echo "$album_urls" | sed -e 's/^\s*<a href="\///g' -e 's/">$//g')

for album in $album_urls; do
    albscrape "$root_url/$album"
done
