#!/bin/sh
rm -rf "$HOME/"{Steam,Documents,Desktop,.xonotic,.steam,.mozilla,.dbus,.pulse-cookie,.pki,.gnome,.kde,.python_history,Downloads,.wget-hsts,.BurpSuite,.java,.gem,.ghidra,.mysql_history,.google-cookie,.hetty,.crawl,morgue,saves,MuseScore*,Music,Pictures,Public,Templates,Videos}
rm -rf "$HOME/".cache/*

# *.log isn't cleared because that could be counter productive
rm -f ./{*.aux,*.ctn,*.idx,*.ilg,*.ind}

# screenshots
rm -f ~/pictures/screens/*

# Clean the SSH cache
echo > "$HOME/".ssh/known_hosts
