#!/bin/sh

# Clean the various random home directory thingies
rm -rf "$HOME/"{Steam,Documents,Desktop,.xonotic,.steam,.mozilla,.dbus,.pulse-cookie,.pki,.gnome,.kde,.python_history,Downloads,.wget-hsts,.BurpSuite,.java,.gem,.ghidra,.mysql_history,.google-cookie,.hetty,.crawl,morgue,saves,MuseScore*,Music,Pictures,Public,Templates,Videos}
rm -rf "$HOME/".cache/*

# *.log isn't cleared because that could be counter productive
rm -f ./{*.aux,*.ctn,*.idx,*.ilg,*.ind}

# Clean up the screenshots
rm -f ~/pictures/screens/*

# Clean the SSH cache
echo > "$HOME/".ssh/known_hosts

# Clean the .config directory
rm -rf "$HOME/.config/"{Electron,dconf,gtk-3.0,mozilla,pulse,rc,transmission,QtProject.conf,kritadisplayrc,kritarc,mimeapps.list,pavucontrol.ini}

# Clean the share directory
rm -rf "$HOME/.local/share/"{applications,flatpak,krita,man,krita-sysinfo.log,krita.log,recently-used.xbel}
