#!/bin/sh


# If another instance is running, simply signal it to reload and exit.
PNAME=$(basename "$0")
RELOAD_REQUESTED=0
trap 'RELOAD_REQUESTED=1' USR1

for pid in $(pgrep -u "$USER" "^$PNAME$"); do
    [ "$pid" != "$$" ] && kill -USR1 "$pid"
done

pgrep -u "$USER" "^$PNAME$" | grep -qv "^$$$" && exit 0


switch_foot() {
    init_file="$XDG_CONFIG_HOME/foot/init-color-theme"

    if ! [ -f "$init_file" ]; then
        echo "initial-color-theme=dark" > "$init_file"
    fi

    if should_use_light; then
        sed -i "s/initial-color-theme=dark/initial-color-theme=light/" \
            "$init_file"
        pkill -u "$USER" --signal=SIGUSR2 '^foot$'
    else
        sed -i "s/initial-color-theme=light/initial-color-theme=dark/" \
            "$init_file"
        pkill -u "$USER" --signal=SIGUSR1 '^foot$'
    fi
}

switch_nvim() {
    for s in /run/user/$(id -u)/nvim.*; do
        [ -S "$s" ] || continue
        nvim --server "$s" --remote-send \
            '<Cmd>call globals#apply_colorscheme_from_system()<CR>'
    done
}

switch_todo() {
    pkill -u "$USER" --signal=SIGUSR1 '^todo_bg$'
}

while true; do
    RELOAD_REQUESTED=0

    # Execute the thingies.
    switch_foot
    switch_nvim
    switch_todo

    next=$(should_use_light)
    [ -z "$next" ] && exit

    # Sleep, but stay interruptible.
    while [ "$next" -gt 0 ]; do
        sleep 1
        next=$((next - 1))

        # If signal received, restart loop immediately.
        [ "$RELOAD_REQUESTED" -eq 1 ] && break
    done
done
