#!/bin/sh

! [ "$EUID" = "0" ] && echo "This script requires root privileges" && exit

# Use the cloudflare dns resolver
grep "^nameserver 1.1.1.1" /etc/resolv.conf &>/dev/null
[ $? = 1 ] && echo "nameserver 1.1.1.1" > /etc/resolv.conf
grep "^nohook resolv.conf" /etc/dhcpcd.conf &>/dev/null
[ $? = 1 ] && echo "nohook resolv.conf" >> /etc/dhcpcd.conf

# Clean up the chains
iptables -F
iptables -X

# Default rules
iptables -P INPUT DROP
iptables -P FORWARD DROP
iptables -P OUTPUT ACCEPT

# Allow established connections and loopback
iptables -A INPUT -m conntrack --ctstate RELATED,ESTABLISHED -j ACCEPT
iptables -A INPUT -i lo -j ACCEPT

# Drop invalid packets
iptables -A INPUT -m conntrack --ctstate INVALID -j DROP

# Allow ICMP packets
iptables -A INPUT -p icmp -j ACCEPT

# Allow LAN connections
tempfile="$(mktemp)"
ip addr show | grep "inet " | awk '{print $2}' > "$tempfile"
for addr in $(cat "$tempfile"); do
    iptables -A INPUT -s $addr -j ACCEPT
done
rm "$tempfile"

# Stuff that falls through gets rejected
iptables -A INPUT -j REJECT --reject-with icmp-proto-unreachable
