#!/bin/sh
jq -r --arg val "$1" '
  def tojsonval:
    (try (fromjson) catch $val);
  tojsonval as $v |
  path(.. | select(
    (. == $v) or
    ((type == "number" and ($v|type == "string") and (. == ($v | tonumber? // ""))) )
  ))
  | map(if type == "string" then "." + . else "[" + tostring + "]" end) | join("")
'
