#!/bin/sh

MUSICROOT="$HOME/music"

# Useful as shit
usage() {
    echo "Usage: $0 <-u url> [-a author] [-l album] [-m]"
    exit
}

url=""
author=""
album=""
mp3=""

# Get the arguments
while getopts "hu:a:l:m" opt; do
    case "$opt" in
        h) usage;;
        u) url="$OPTARG";;
        a) author="$OPTARG";;
        l) album="$OPTARG";;
        m) mp3="--audio-format mp3"
    esac
done

[ "$url" = "" ] && usage

# Youtube doesn't like tor connections :>
case "$url" in
    "https://www.youtube.com"*|"https://music.youtube.com"*) proxy='';;
    *)                          proxy='--proxy socks5://localhost:9050'
esac

yt-dlp $proxy -x $mp3 -o "$MUSICROOT/$author/$album/%(playlist_index)s %(title)s.%(ext)s" "$url"
