#!/bin/sh

read light_time dark_time <<EOF
$(solcalc)
EOF

now=$(date +%s)

light=$(date -d "today $light_time" +%s)
dark=$(date -d "today $dark_time" +%s)

# normalize wrap
[ "$dark" -lt "$light" ] && dark=$((dark + 86400))

if [ "$now" -ge "$light" ] && [ "$now" -lt "$dark" ]; then
    next=$dark
    status=0
else
    if [ "$now" -lt "$light" ]; then
        next=$light
    else
        next=$(date -d "tomorrow $light_time" +%s)
    fi
    status=1
fi

echo $((next - now))
exit $status
