#!/bin/sh

[ "$1" = "" ] && exit

word=$1

curl -Gs "https://words.bighugelabs.com/$word" |
awk '
    /<h3>/ {
        gsub(/.*<h3>|<\/h3>.*/, "")
        print ""
        print $0 ":"
        next
    }

    /<li><a / {
        gsub(/.*<a[^>]*>|<\/a>.*/, "")
        print "  " $0
    }
'
