#!/bin/sh

# This is the default microphone that will be muted if the soundboard is
# detected as the default source for the system. This way we mute this
# microphone instead of the whole soundboard.
# If, however, the soundboard is not detected, the default source will be used
# instead of this one
DEFAULT_MIC="alsa_input.usb-TEAC_Corporation_TASCAM_DR_Series-00.analog-stereo"

# Use the provided source if soundboard is on, otherwise use the default source
SOURCE="@DEFAULT_SOURCE@"
pactl get-default-source | grep -q "soundboard" && SOURCE="$DEFAULT_MIC"

# Get the path to the mute sound effect
SCRIPT_DIR=$(dirname "$(realpath "$0")")
SOUND_EFFECT="$SCRIPT_DIR/../mic_check.mp3"

# Get current volume (any channel, numeric only)
VOLUME=$(pactl get-source-volume "$SOURCE" \
    | awk '/Volume:/ {gsub("%","",$5); print $5; exit}')

# Toggle mic; play sound effect on unmute
if [ "$VOLUME" -gt 0 ]; then
    # Mic is ON -> mute
    pactl set-source-volume "$SOURCE" "0%"
else
    # Mic is OFF -> play sound effect and unmute the mic
    setsid mpv "$SOUND_EFFECT" --volume=130 >/dev/null 2>&1 &
    pactl set-source-volume "$SOURCE" "100%"
fi
