#!/bin/sh

pushd "$(mktemp -d)"

wget 'https://discord.com/api/download?platform=linux&format=tar.gz'
tar -xvf 'download?platform=linux&format=tar.gz'

mv ./Discord/Discord ./Discord/discord
mv ./Discord/* "$HOME"/.config/discord/
