#!/bin/sh

if ! groups | grep rustusers &>/dev/null; then
    echo "You're not part of the 'rustusers' group!"
    exit 1
fi

install_crates() {
    cargo install --locked tokei cargo-info tokio-console cargo-expand ripgrep \
        cargo-show-asm
}


RUST_DIR="/opt/rust"
if [ -d "$RUST_DIR/cargo" ]; then
    rustup update
    install_crates
else
    echo "Installing rust!"

    # Create the rust directory
    sudo mkdir -p "$RUST_DIR"
    sudo chown :rustusers "$RUST_DIR"
    sudo chmod 770 "$RUST_DIR"
    sudo chmod g+s "$RUST_DIR"

    # Download and execute rustup
    curl --proto '=https' --tlsv1.2 -sSf 'https://sh.rustup.rs' \
        | sh -s -- -y --no-modify-path --default-toolchain nightly

    # Install the crates
    source "$RUST_DIR/cargo/env"
    install_crates
fi
