#!/bin/sh

# Get the actual wmenu executable path
PATH_WITHOUT_SELF=$(printf "%s" "$PATH" \
    | awk -v RS=: -v ORS=: '$0 != "'"$(dirname "$0")"'" {print}' \
    | sed 's/:$//')
wmenu_run=$(PATH="$PATH_WITHOUT_SELF" command -v wmenu-run)

eval "$wmenu_run $WMENU_ARGS \"\$@\""
