#!/bin/sh

url="$1"
[ "$url" = "" ] && exit

echo "Extracting info"
json=$(yt-dlp -j --no-playlist "$url")
artist=$(echo "$json" | jq -r '.artist')
title=$(echo "$json" | jq -r '.title')

if [ "$artist" = "null" ]; then
    echo "Can't extract info"
    exit 1
fi

ym "$artist" "$title" "$url"
