#!/bin/sh

# Help message
print_help() {
    echo "Usage: $0 <youtube_music_channel_url>"
    echo
    echo "    Scrapes albums and EPs from a YouTube Music channel and outputs a"
    echo "    shell script that can download them using yt-dlp."
    echo
    echo "    The URL must be a valid YouTube Music channel link like:"
    echo "        https://music.youtube.com/channel/UCXXXXXXXXXXXX"
    echo
    echo "Example:"
    echo "    $0 \"https://music.youtube.com/channel/UCfkOw3FuazQrUHTbp8a01_g\" > download_albums.sh"
    echo "    chmod +x download_albums.sh"
    echo "    ./download_albums.sh"
    echo
    echo "To speed up downloads by running them in parallel, add '&' at the end of the"
    echo "'download' call in the generated script:"
    echo
    echo "    download \"\$uri\" &"
    echo
    echo "Then run the script and optionally limit concurrency like so:"
    echo "    ./download_albums.sh; wait"
}

channel_id="$1"

# Check that an ID was provided
[ "$channel_id" = "" ] && print_help && exit

# Extract the ID; either the full channel url was provided, or an ID that still
# has to be extracted.
case "$channel_id" in
    *"://"*)
        channel_id=$(basename "$channel_id")
        ;;
    *)
        channel_id=$(ytid "$channel_id" | sed '1!d')
        ;;
esac

channel_id="${channel_id#??}"

# Get the discography listing
json=$(curl 'https://music.youtube.com/youtubei/v1/browse' \
  --compressed \
  -X POST \
  -H 'User-Agent: Mozilla/5.0' \
  -H 'Accept: application/json' \
  -H 'Content-Type: application/json' \
  --data-raw "$(jq -c -n \
      --arg date "$(date +%Y%m01)" \
      --arg browse_id "MPADUC$channel_id"  \
    '{
        "context": {
            "client": {
                "clientName": "WEB_REMIX",
                "clientVersion": ("1." + $date + ".00.00")
            }
        },
        "browseId": $browse_id
    }'
)")


# Get the channel/artist name. This will be used as the main artist tag for all
# albums. The actual album artist (often different or featuring others) will go
# in the composer tag. This keeps all albums grouped under one artist
# (e.g. MF DOOM) even if they have multiple contributors.
artist="$(echo $json | jq -r '.header.musicHeaderRenderer.title.runs[0].text')"
artist_regex=$(printf '%s' "$artist" | sed -e 's/[][\/.^$*+?{}()|"]/\\&/g')
artist=$(printf '%s' "$artist" | sed 's/\\/\\\\/g; s/"/\\"/g; s/\$/\\\$/g')

# Get the required fields and only keep EPs and albums
listing=$(echo "$json" | jq '
    .contents
    .singleColumnBrowseResultsRenderer
    .tabs[0]
    .tabRenderer
    .content
    .sectionListRenderer
    .contents[0]
    .gridRenderer
    .items[]
    | .musicTwoRowItemRenderer
    | {
        title: .title.runs[0].text,
        kind: .subtitle.runs[0].text,
        date: .subtitle.runs[2].text,
        uri: .navigationEndpoint.browseEndpoint.browseId | sub("^MPREb_"; ""),
    }
    | select(.kind == "EP" or .kind == "Album")
')

# Extract the URIs
uris_dates=$(echo $listing | jq -s '.[] | .uri + " " + .date')

echo '#!/bin/sh'
echo
echo "artist='$artist'"
echo
echo 'while IFS= read -r line; do'
echo '    IFS="│"; set -- $(printf "%s\n" "$line")'
echo '    ident=$(echo "$1" | sed -e "s/^ *//; s/ *$//")'
echo '    date=$(echo "$2" | sed -e "s/^ *//; s/ *$//")'
echo '    album=$(echo "$4" | sed -e "s/^ *//; s/ *$//")'
echo '    url="https://music.youtube.com/browse/MPREb_$ident"'
echo
echo '    musicdl -u "$url" -a "$artist" -l "$album" -d "$date" -m &'
echo 'done << ───────────────────┤'
echo "$listing" | jq -s -r '.[] | .uri + " │ " + .date + " │ " + (.kind | if . == "EP" then "EP   " else . end) + " │ " + .title'
echo '───────────────────┤'
echo '# PICK YOUR POISON │'
echo '#──────────────────┘'
