#!/bin/sh

main_url="$1"

# Help message
print_help() {
    echo "Usage: $0 <youtube_music_channel_url>"
    echo
    echo "    Scrapes albums and EPs from a YouTube Music channel and outputs a"
    echo "    shell script that can download them using yt-dlp."
    echo
    echo "    The URL must be a valid YouTube Music channel link like:"
    echo "        https://music.youtube.com/channel/UCXXXXXXXXXXXX"
    echo
    echo "Example:"
    echo "    $0 \"https://music.youtube.com/channel/UCfkOw3FuazQrUHTbp8a01_g\" > download_albums.sh"
    echo "    chmod +x download_albums.sh"
    echo "    ./download_albums.sh"
    echo
    echo "To speed up downloads by running them in parallel, add '&' at the end of the"
    echo "'download' call in the generated script:"
    echo
    echo "    download \"\$uri\" &"
    echo
    echo "Then run the script and optionally limit concurrency like so:"
    echo "    ./download_albums.sh; wait"
}

# Check that a url was provided
[ "$main_url" = "" ] && print_help && exit

# Get the channel ID
channel_id=$(echo "$main_url" | sed \
    -e 's/\/browse\//\/channel\//g' \
    -e 's/\/channel\/MPADUC/\/channel\/UC/g' \
    -e 's/.*music.youtube.com\/channel\/UC\(.*\)?*.*/\1/g')

# Make sure that we got the correct channel ID.
# Technically `wc -c` should be better here, but this is more future proof
if echo $channel_id | grep -q "://"; then
    echo "Not a channel url"
    exit
fi

# Get the discography listing
json=$(curl 'https://music.youtube.com/youtubei/v1/browse' \
  --compressed \
  -X POST \
  -H 'User-Agent: Mozilla/5.0' \
  -H 'Accept: application/json' \
  -H 'Content-Type: application/json' \
  --data-raw "$(jq -c -n \
      --arg date "$(date +%Y%m01)" \
      --arg channel_id "MPADUC$channel_id"  \
    '{
        "context": {
            "client": {
                "clientName": "WEB_REMIX",
                "clientVersion": ("1." + $date + ".00.00")
            }
        },
        "browseId": $channel_id
    }'
)")

# Get the channel/artist name. This will be used as the main artist tag for all
# albums. The actual album artist (often different or featuring others) will go
# in the composer tag. This keeps all albums grouped under one artist
# (e.g. MF DOOM) even if they have multiple contributors.
artist="$(echo $json | jq -r '.header.musicHeaderRenderer.title.runs[0].text')"
artist_regex=$(printf '%s' "$artist" | sed -e 's/[][\/.^$*+?{}()|"]/\\&/g')
artist=$(printf '%s' "$artist" | sed 's/\\/\\\\/g; s/"/\\"/g; s/\$/\\\$/g')

# Get the required fields and only keep EPs and albums
listing=$(echo $json | jq '
    .contents
    .singleColumnBrowseResultsRenderer
    .tabs[0]
    .tabRenderer
    .content
    .sectionListRenderer
    .contents[0]
    .gridRenderer
    .items[]
    | .musicTwoRowItemRenderer
    | {
        title: .title.runs[0].text,
        kind: .subtitle.runs[0].text,
        date: .subtitle.runs[2].text,
        uri: .navigationEndpoint.browseEndpoint.browseId | sub("^MPREb_"; ""),
    }
    | select(.kind == "EP" or .kind == "Album")')

# Extract the URIs
uris_dates=$(echo $listing | jq -s '.[] | .uri + " " + .date')

echo '#!/bin/sh'
echo
echo 'MUSIC_ROOT="$HOME/music"'
echo
echo 'download() {'
echo '    url="https://music.youtube.com/channel/MPREb_$1"'
echo '    date="$2"'
echo
echo '    yt-dlp -x --audio-format mp3 --embed-metadata \'
echo '        -o "$MUSIC_ROOT/%(artist)s/%(album)s/%(playlist_index)s %(title)s.%(ext)s" \'
echo '        --parse-metadata ":(?P<meta_description>)" \'
echo '        --parse-metadata ":(?P<meta_synopsis>)" \'
echo '        --parse-metadata ":(?P<meta_purl>)" \'
echo '        --parse-metadata "playlist_index:%(meta_track)s" \'
echo '        --parse-metadata "playlist_title:(?:Album - )?(?P<album>.+)" \'
echo '        --parse-metadata "$date:%(meta_date)s" \'
echo '        --parse-metadata "artist:%(composer)s" \'
echo "        --replace-in-metadata \"artist\" \"^.*$\" \"$artist\" \\"
echo "        --replace-in-metadata \"composer\" \"(?i)$artist_regex(?:, )?\" \"\" \\"
echo "        --replace-in-metadata \"composer\" \", *$\" \"\" \\"
echo '        "$url"'
echo '}'
echo
echo 'while IFS= read -r line; do'
echo '    IFS="│"; set -- $(printf "%s\n" "$line")'
echo '    ident=$(echo "$1" | sed -e "s/^ *//; s/ *$//")'
echo '    date=$(echo "$2" | sed -e "s/^ *//; s/ *$//")'
echo '    download "$ident" "$date"'
echo 'done << ───────────────────┤'
echo "$listing" | jq -s -r '.[] | .uri + " │ " + .date + " │ " + (.kind | if . == "EP" then "EP   " else . end) + " │ " + .title'
echo '───────────────────┤'
echo '# PICK YOUR POISON │'
echo '#──────────────────┘'
